[package]
edition = "2021"
name = "music_stats"
version = "0.1.0"

[dependencies]
demand = "1.2.4"
regex = "1.11.1"
reqwest = {version="0.12.9", features = ["json"]}
serde = {version = "1.0.214", features = ["derive"]}
serde_json = "1.0.132"
tokio = {version = "1.41.1", features = ["full"]}
